# Site settings
title: Glauber Barbosa Porto
description: Glauber Porto CV
favicon: /assets/img/avatar.JPG
baseurl: https://glauberporto.github.io/resumecard
url: https://glauberporto.github.io/resumecard
#url: https://glauberporto.github.io/resumecard
rss_url: /pages/atom.xml
# google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Glauber Barbosa Porto
  title: Tecnologia da Informação
  address: Belo Horizonte, Minas Gerais - BR
  email: glauberporto@gmail.com
  link: 
  weibo:
  github: glauberporto
  linkedin: glauberporto
  twitter: glauber_porto
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: Serviço Nacional de Aprendizagem Comercial (SENAC-MG)
      location: Belo Horizonte, Minas Gerais
      title: Tecnico em Informatica
      started: 2012
      duration: (Atual)
      description: Gerenciamento da Rede, Gerenciamento e Implantação de Servidores, Manutenção e Configuração em Desktop e Notebooks, Monitoramento da Rede, Suporte Tecnico via Ferramenta de Atendimento(HELP-DESK) e Backup
    - work2:
      company: XXX Ltd
      location: Shanghai, China
      title: Java Developer
      started: 2012
      duration: (2012 - 2014)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work3:
      company: XXX Ltd
      location: Shanghai, China
      title: Java Developer
      started: 2009
      duration: (2009 - 2012)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  educationHistory:
    - education1:
      organization: XXXXXX University
      location: Shenyang, China
      degree: Bachelor
      major: Software Engineering
      started: 2005
      duration: (2005 - 2009)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  languages:
    - language1:
      name: Ingles
      proficiency: Basico
  programmingSkills:
    - skill1:
      name: Servidores Linux
      percentage: 90%
    - skill2:
      name: Servidores Windows
      percentage: 90%
    - skill3:
      name: Redes
      percentage: 90%
    - skill4:
      name: Firewall
      percentage: 80%
    - skill5:
      name: Virtualização
      percentage: 80%
    - skill6:
      name: Backup
      percentage: 80%
    - skill7:
      name: Desktops / Notebooks
      percentage: 90%
    - skill8:
      name: PowerShell
      percentage: 25%
    - skill9:
      name: Python
      percentage: 25%
